VOICE_PLAY = 'play'
VOICE_STOP = 'stop'
VOICE_PAUSE = 'pause'
VOICE_UNPAUSE = 'unpause'
VOICE_VOLUME_UP = 'volume up'
VOICE_VOLUME_DOWN = 'volume down'
VOICE_BACK = 'back'
VOICE_FORWARD = 'forward'
VOICE_FULL = 'full speed'
VOICE_HALT = 'halt'
VOICE_STOP = 'stop'
VOICE_LEFT = 'left'
VOICE_RIGHT = 'right'
VOICE_HALF = 'half speed'

