PLAY = 'play'
STOP = 'stop'
PAUSE = 'pause'
UNPAUSE = 'unpause'
VOLUME_UP = 'volume up'
VOLUME_DOWN = 'volume down'

RESET = 'reset'
BEGIN_FIESTA = 'begin fiesta'
END_FIESTA = 'end fiesta'
BEGIN_FOLLOW = 'begin follow'
END_FOLLOW = 'end follow'
BEGIN_LOCATION = 'begin location'
END_LOCATION = 'end location'

MOVE_POSITION = 'goto'
MOVE_REGION = 'move region'
SAVE_POSITION = 'save position'
SAVE_REGION = 'save region'
DELETE_POSITION = 'delete'
DELETE_REGION = 'delete'
LIST_POSITION = 'list position'
LIST_REGION = 'list region'
PRINT_POSITION = 'print position'
PRINT_REGION = 'print region'
SAVE_THIS = 'save this'
WHERE_AM_I = 'where am i'
